---
- name: install desktop packages
  pacman:
    name:
      - sway
      - swaybg
      - xorg-server-xwayland
      - waybar
      - mako
      - kanshi # autorandr for wayland
      - grim # screenshots
      - slurp # region selector
      - wl-clipboard # clipboard manager
      - swayidle
      - xdg-user-dirs
    state: present

- name: install video packages
  pacman:
    name:
      - mesa
      - mesa-demos
      - lib32-virtualgl
    state: present

- name: install audio packages
  pacman:
    name:
      - pulseaudio
      - pulseaudio-alsa
      - pavucontrol
      - pamixer
      - alsa-utils
    state: present

- name: install applications packages
  pacman:
    name:
      - imv # img visualizer
      - kitty # terminal emulator
      - code # code editor
      - evince # pdf viewer
      - firefox
      - firefox-i18n-fr
      - gimp # img editor
      - kolourpaint # img editor
      - lollypop # music player
      - lxappearance # theme manager
      - mpv # video player
      - thunar # file manager
      - openvpn
      - playerctl # music player cli controller
      - rdesktop # remote desktop client
      - steam # games manager
      - transmission-gtk # torrent downloader
      - variety # random backgrounds
      - papirus-icon-theme # icon theme
      - x2goclient 
      - youtube-dl
    state: present

- name: add missing gpg keys for aur
  become: no
  shell: gpg --recv '{{item}}'
  loop:
    # spotify
    - 4773BD5E130D1D45
    # wob
    - F4B432D5D67990E3

  changed_when: false

- name: install aur packages
  become: no
  aur:
    skip_installed: true
    name:
      - adapta-gtk-theme #https://github.com/Alexays/Waybar/issues/515
      - android-sdk
      - android-sdk-build-tools
      - android-sdk-platform-tools
      - android-platform
      - android-emulator
      - android-support-repository
      - android-studio
      - equilux-theme 
      #- wdisplays-git # arandr for wayland
      - wf-recorder-git # screen recorder for wayland
      - grimshot-git # grim+slurp wrapper
      - wofi-hg # rofi for wayland
      - swaylock-fancy-git # locker for wayland
      - wob # bars for wayland
      - connman-gtk # connman gtk gui
      - gnome-ssh-askpass2 # ssh askpass gui
      - google-chrome
      - laptop-mode-tools
      - adb-sync-git # android dir sync
      - downgrade # package downgrader
      - lf # cli file manager
      - light-git # brightness manager
      - mindustry-bin # game
      - minecraft-launcher # game
      - molotov # french tv wrapper
      - openvpn-update-systemd-resolved # TORM ?
      - otf-font-awesome
      - pastel # color viewer
      - spotify # music player
      - teams # Microsoft Teams
        #- tiny-irc-client-git
      - starleaf-breeze
      - zoom
- name: Ensure group "android-sdk" exists
  group:
    name: android-sdk
    state: present
- name: Add user groups
  user:
    name: '{{user}}'
    groups: android-sdk,wheel,input,uucp,storage
    append: yes
