---
- name: add sudo conf for aur
  tags: always
  lineinfile:
    path: /etc/sudoers
    line: '{{user}} ALL=(ALL) NOPASSWD: ALL'

- name: install AUR helper
  become: no
  aur:
    name: trizen
    use: makepkg
    skip_installed: true
